use_frameworks!

platform :ios, '8.0'

target 'MyComponentA_Example' do
  pod 'MyComponentA'
  pod 'MyTestRouter',"~> 0.1.1"

  target 'MyComponentA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
